/* =========================================================================
   PYCMAR · DATA + i18n
   Catálogo real extraído del PDF oficial. Bilingüe ES/EN.
   Exposed on window.PY
   ========================================================================= */
(function () {
  // ---- Empresa --------------------------------------------------------------
  const company = {
    name: "PYCMAR",
    legal: "Pycmar Export Perú",
    tagline_es: "Procesos y Congelados del Mar",
    tagline_en: "Seafood Processing & Frozen Products",
    email: "Pycmarperu@gmail.com",
    phone: "+51 987 486 981",
    phoneRaw: "51987486981",
    city: "Lima · Paita · Perú",
  };

  // ---- Categorías -----------------------------------------------------------
  const categories = [
    { id: "pota",       es: "Pota",            en: "Giant Squid",   count: 14, icon:"squid",
      desc_es: "Dosidicus gigas — el corazón de nuestra exportación.",
      desc_en: "Dosidicus gigas — the core of our export line." },
    { id: "calamar",    es: "Calamar y Sepia", en: "Squid & Cuttlefish", count: 2, icon:"rings",
      desc_es: "Loligo entero y sepia, congelado en bloque o IQF.",
      desc_en: "Whole loligo and cuttlefish, block-frozen or IQF." },
    { id: "pescado",    es: "Pescados",        en: "Fish",          count: 10, icon:"fish",
      desc_es: "Pelágicos y de fondo, enteros, HGT y en filete.",
      desc_en: "Pelagic and demersal — whole, HGT and filleted." },
    { id: "marisco",    es: "Mariscos",        en: "Shellfish",     count: 5, icon:"shrimp",
      desc_es: "Pulpo, langosta y concha de abanico de primera.",
      desc_en: "Octopus, lobster and premium scallops." },
    { id: "ovas",       es: "Ovas",            en: "Roe",           count: 1, icon:"roe",
      desc_es: "Ovas de pez volador en bloque, sin ovas negras.",
      desc_en: "Flying fish roe in block, no black roe." },
    { id: "preparado",  es: "Preparados",      en: "Value-Added",   count: 2, icon:"utensils",
      desc_es: "Prefritos y mixtos listos para servicio.",
      desc_en: "Pre-fried and ready-to-serve seafood mixes." },
  ];

  // ---- Helper compacto ------------------------------------------------------
  const P = (o) => o;

  // tag types: IQF, Bloque, Cocido, Prefrito  → chips
  const products = [
    // ----- POTA / GIANT SQUID -----
    P({ id:"botones", cat:"pota", es:"Botones de Pota", en:"Giant Squid Buttons",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF","Bloque"], price:16.5, featured:true, retail:true,
      pres_es:"Con o sin membrana", pres_en:"On/off membrane",
      measure_es:"Grosor 0,7–1,5 cm · Diámetro 2,2 cm", measure_en:"Thickness 0.7–1.5 cm · Diameter 2.2 cm",
      pack_es:"IQF a granel en cajas de 15 kg (3 bolsas de 5 kg) · Bloques en saco de 20 kg (2×10 kg)",
      pack_en:"Bulk IQF in 15 kg boxes (3×5 kg) · Blocks in 20 kg bag (2×10 kg)",
      blurb_es:"Anillos cerrados de manto, parejos y firmes. El formato más versátil para anticuchos y salteados.",
      blurb_en:"Closed mantle rings, even and firm. The most versatile cut for grilling and stir-fry." }),
    P({ id:"recortes", cat:"pota", es:"Recortes de Pota", en:"Giant Squid Bits & Pieces",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:11.0, retail:true,
      pres_es:"Con o sin membrana", pres_en:"On/off membrane",
      pack_es:"Saco de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bag: 2 blocks of 10 kg",
      blurb_es:"Trozos de manto ideales para mezclas, conservas y harinas proteicas.",
      blurb_en:"Mantle pieces ideal for blends, canning and protein meal." }),
    P({ id:"filete", cat:"pota", es:"Filete de Pota", en:"Giant Squid Fillet",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:14.0, featured:true, retail:true,
      sizes_es:"De 1 a 2 kg · de 2 a 4 kg", sizes_en:"1–2 kg · 2–4 kg",
      measure_es:"Grosor 1,8–2,3 cm", measure_en:"Thickness 1.8–2.3 cm",
      pres_es:"Con membrana y telilla o sin", pres_en:"On/off membrane or inner layer",
      pack_es:"Saco de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bag: 2 blocks of 10 kg",
      blurb_es:"Manto abierto en lámina entera. Base para anillas, tiras y porciones a medida.",
      blurb_en:"Open whole mantle sheet. The base for rings, strips and custom portions." }),
    P({ id:"daruma", cat:"pota", es:"Daruma (Boin Boiled Fillet)", en:"Daruma — Boiled Fillet",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque","Cocido"], price:19.0, retail:true,
      measure_es:"Grosor 0,8–1,2 cm", measure_en:"Thickness 0.8–1.2 cm",
      pres_es:"Cocido · sin membrana ni telilla", pres_en:"Cooked · membrane & inner layer off",
      pack_es:"Saco de 21 kg: 3 bloques de 7 kg", pack_en:"21 kg bag: 3 blocks of 7 kg",
      blurb_es:"Filete precocido estilo japonés, listo para mercados premium de Asia.",
      blurb_en:"Japanese-style pre-cooked fillet, ready for premium Asian markets." }),
    P({ id:"steak-oval", cat:"pota", es:"Steak Oval de Pota IQF", en:"Oval Squid Steak IQF",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF"], price:17.5, retail:true,
      measure_es:"Grosor 0,85–1,2 cm", measure_en:"Thickness 0.85–1.2 cm",
      pres_es:"Sin membrana ni telilla", pres_en:"Membrane & inner layer off",
      pack_es:"Caja de 30 lb: 6 cajas de 5 lb", pack_en:"30 lb box: 6 boxes of 5 lb",
      blurb_es:"Steak ovalado de corte limpio, presentación de retail.",
      blurb_en:"Clean-cut oval steak, retail-ready presentation." }),
    P({ id:"valencia", cat:"pota", es:"Filete Corte Valencia", en:"Valencia Fillet Cut",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:15.5, retail:true,
      measure_es:"Largo 15–25 cm · ancho 8–12 cm · grosor 0,8–1,2 cm", measure_en:"Length 15–25 cm · width 8–12 cm · thickness 0.8–1.2 cm",
      pres_es:"Sin membrana ni telilla", pres_en:"Membrane & inner layer off",
      pack_es:"Saco/caja de 20 kg (2×10 kg) · 22,5 kg (3×7,5 kg)", pack_en:"20 kg bag/box (2×10 kg) · 22.5 kg (3×7.5 kg)",
      blurb_es:"Corte rectangular calibrado para el mercado español.",
      blurb_en:"Calibrated rectangular cut for the Spanish market." }),
    P({ id:"anillas", cat:"pota", es:"Anillas de Pota", en:"Giant Squid Rings",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF","Bloque"], price:18.0, featured:true, retail:true,
      measure_es:"Diám. ext. 4,5–7 cm · int. 2,2–4,5 cm", measure_en:"Outer 4.5–7 cm · inner 2.2–4.5 cm",
      pres_es:"Anillas blancas o amarillas, con o sin membrana", pres_en:"White or yellow rings, on/off membrane",
      pack_es:"Bloque 26 kg (4×6,5 kg) · IQF a granel 10 kg (4×2,5 kg)", pack_en:"Block 26 kg (4×6.5 kg) · Bulk IQF 10 kg (4×2.5 kg)",
      blurb_es:"Anillas calibradas, blancas o amarillas, para empanizado y conserva.",
      blurb_en:"Calibrated rings, white or yellow, for breading and canning." }),
    P({ id:"alas", cat:"pota", es:"Alas de Pota", en:"Giant Squid Wings",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:12.5, retail:true,
      sizes_es:"300 gr a más", sizes_en:"300 gr up",
      pres_es:"Enteras, corte por la mitad o en cruz", pres_en:"Whole, half or cross cut",
      pack_es:"Saco de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bag: 2 blocks of 10 kg",
      blurb_es:"Aleta lateral del manto, textura firme y rendidora.",
      blurb_en:"Lateral mantle fin, firm and high-yield." }),
    P({ id:"nucas", cat:"pota", es:"Nucas de Pota", en:"Giant Squid Necks",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:13.0, retail:true,
      sizes_es:"100–300 · 300–500 · 500–700 gr · 700 gr a más", sizes_en:"100–300 · 300–500 · 500–700 gr · 700 gr up",
      pack_es:"Saco de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bag: 2 blocks of 10 kg",
      blurb_es:"Unión cabeza-manto, carnosa, para guisos y mixturas.",
      blurb_en:"Head-mantle joint, meaty, for stews and blends." }),
    P({ id:"tentaculos", cat:"pota", es:"Tentáculos de Pota", en:"Giant Squid Tentacles",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:13.5, retail:true,
      pres_es:"Corte bailarina, sin uñas ni ventosas", pres_en:"Ballerina cut, nails & suckers off",
      pack_es:"Saco de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bag: 2 blocks of 10 kg",
      blurb_es:"Corte bailarina limpio, sin uñas ni ventosas.",
      blurb_en:"Clean ballerina cut, no nails or suckers." }),
    P({ id:"rodaja-rejo", cat:"pota", es:"Rodajas de Rejo", en:"Giant Squid Tentacle Slices",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF","Cocido"], price:21.0, retail:true,
      measure_es:"Alto 0,2–0,8 cm · diámetro 1,5–3,5 cm", measure_en:"Height 0.2–0.8 cm · diameter 1.5–3.5 cm",
      pres_es:"Cocido · glaseo a la carta", pres_en:"Cooked · customizable glazing",
      pack_es:"IQF bolsas 500 gr–1 kg o cajas a granel 7 kg", pack_en:"IQF 500 gr–1 kg bags or bulk 7 kg boxes",
      blurb_es:"Rodaja cocida de rejo, lista para tapas y ensaladas.",
      blurb_en:"Cooked tentacle slice, ready for tapas and salads." }),
    P({ id:"dados", cat:"pota", es:"Dados de Pota IQF", en:"Giant Squid Cubes IQF",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF"], price:15.0, retail:true,
      measure_es:"Alto 2 cm · ancho 2 cm · grosor natural", measure_en:"Height 2 cm · width 2 cm · natural thickness",
      pres_es:"Con o sin membrana", pres_en:"On/off membrane",
      pack_es:"A granel cajas 7 kg o bolsas 500 gr–1 kg", pack_en:"Bulk 7 kg boxes or 500 gr–1 kg bags",
      blurb_es:"Cubo regular de 2 cm, ideal para brochetas y mixtos.",
      blurb_en:"Even 2 cm cube, ideal for skewers and mixes." }),
    P({ id:"rabas", cat:"pota", es:"Rabas de Pota IQF", en:"Giant Squid Sticks IQF",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF"], price:15.5, featured:true, retail:true,
      measure_es:"Largo 6–8 cm · ancho 1 cm · grosor natural", measure_en:"Length 6–8 cm · width 1 cm · natural thickness",
      pres_es:"Con o sin membrana y telilla", pres_en:"On/off membrane & inner layer",
      pack_es:"A granel cajas 7 kg o bolsas 500 gr–1 kg", pack_en:"Bulk 7 kg boxes or 500 gr–1 kg bags",
      blurb_es:"Bastón fino para freír — la raba clásica de barra.",
      blurb_en:"Fine stick for frying — the classic bar-style raba." }),
    P({ id:"tiras", cat:"pota", es:"Tiras de Pota IQF", en:"Giant Squid Strips IQF",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF"], price:15.0, retail:true,
      measure_es:"Largo 8–12 cm · ancho 2 cm · grosor natural", measure_en:"Length 8–12 cm · width 2 cm · natural thickness",
      pres_es:"Con o sin membrana y telilla", pres_en:"On/off membrane & inner layer",
      pack_es:"A granel cajas 7 kg o bolsas 500 gr–1 kg", pack_en:"Bulk 7 kg boxes or 500 gr–1 kg bags",
      blurb_es:"Tira ancha para salteados y woks de alto volumen.",
      blurb_en:"Wide strip for stir-fry and high-volume woks." }),

    // ----- CALAMAR / SEPIA -----
    P({ id:"loligo", cat:"calamar", es:"Calamar Loligo", en:"Loligo Squid",
      sci:"Doryteuthis gahi", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:22.0, featured:true, retail:true,
      pres_es:"Entero", pres_en:"Whole",
      pack_es:"Sacos de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bags: 2 blocks of 10 kg",
      blurb_es:"Calamar pota chica entero, dulce y tierno, talla de mercado.",
      blurb_en:"Whole small squid, sweet and tender, market grade." }),
    P({ id:"sepia", cat:"calamar", es:"Sepia", en:"Cuttlefish",
      sci:"Sepia officinalis", fao:"FAO 34", origin_es:"África", origin_en:"Africa",
      tags:["IQF"], price:24.0, retail:true,
      pres_es:"Entero", pres_en:"Whole",
      pack_es:"A granel en cajas, bloque o bolsas de 80 gr a 1 kg", pack_en:"Bulk in boxes, blocks or 80 gr–1 kg bags",
      blurb_es:"Sepia entera IQF, carne blanca y compacta.",
      blurb_en:"Whole IQF cuttlefish, white compact meat." }),

    // ----- PESCADOS / FISH -----
    P({ id:"mahimahi", cat:"pescado", es:"Mahi Mahi (Dorado)", en:"Mahi Mahi (Dorado)",
      sci:"Coryphaena hippurus", fao:"FAO 87", origin_es:"Perú · Ecuador", origin_en:"Peru · Ecuador",
      tags:["IQF"], price:34.0, featured:true, retail:true,
      sizes_es:"Filete con piel 3–5 / 5–7 / 7–9 lb · porciones", sizes_en:"Skin-on fillet 3–5 / 5–7 / 7–9 lb · portions",
      pres_es:"Filetes con piel, flechas sin piel y porciones", pres_en:"Skin-on fillets, skinless fletches & portions",
      pack_es:"IVP en cajas de 25 o 50 lb", pack_en:"IVP in 25 or 50 lb boxes",
      blurb_es:"Dorado de altura, filete firme y bajo en grasa. Estrella de exportación a EE.UU.",
      blurb_en:"Open-water dorado, firm low-fat fillet. An export star to the USA." }),
    P({ id:"anchoveta", cat:"pescado", es:"Anchoveta Peruana", en:"Peruvian Sardine",
      sci:"Engraulis ringens", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:6.5, retail:true,
      sizes_es:"Entera 12 cm/pz a más", sizes_en:"Whole 12 cm/pc up",
      pres_es:"Entera con branquias y vísceras", pres_en:"Whole with gills and viscera",
      pack_es:"Sacos de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bags: 2 blocks of 10 kg",
      blurb_es:"Pelágico azul peruano, alto omega-3, para conserva y curado.",
      blurb_en:"Peruvian blue pelagic, high omega-3, for canning and curing." }),
    P({ id:"sardina-vz", cat:"pescado", es:"Sardina Venezolana", en:"Venezuelan Sardine",
      sci:"Sardinella aurita", fao:"FAO 31", origin_es:"Venezuela", origin_en:"Venezuela",
      tags:["Bloque"], price:7.0, retail:true,
      pres_es:"Entera y eviscerada", pres_en:"Whole and gutted",
      pack_es:"Sacos de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bags: 2 blocks of 10 kg",
      blurb_es:"Sardina del Caribe, entera o eviscerada, lista para conserva.",
      blurb_en:"Caribbean sardine, whole or gutted, canning-ready." }),
    P({ id:"rape", cat:"pescado", es:"Rape (Monkfish)", en:"Monkfish",
      sci:"Lophius americanus", fao:"FAO 34", origin_es:"África", origin_en:"Africa",
      tags:["IQF"], price:38.0, featured:true, retail:true,
      sizes_es:"Cola 250 gr a 2 kg a más", sizes_en:"Tail 250 gr to 2 kg up",
      pres_es:"Entero IWP eviscerado · cola sin piel HGT", pres_en:"Whole IWP gutted · tail skin-off HGT",
      pack_es:"Cajas de 20 kg", pack_en:"20 kg boxes",
      blurb_es:"Cola de rape de carne magra y firme, gourmet europeo.",
      blurb_en:"Lean firm monkfish tail, a European gourmet cut." }),
    P({ id:"cachua", cat:"pescado", es:"Cachua (Leatherjacket)", en:"Leatherjacket Filefish",
      sci:"Aluterus monoceros", fao:"FAO 31", origin_es:"Venezuela", origin_en:"Venezuela",
      tags:["IQF","Bloque"], price:12.0, retail:true,
      sizes_es:"Entero 0,5–6 kg a más", sizes_en:"Whole 0.5–6 kg up",
      pres_es:"HGT o WR", pres_en:"HGT or WR",
      pack_es:"Cajas de 10 kg", pack_en:"10 kg boxes",
      blurb_es:"Pez ballesta de carne blanca, excelente rendimiento en HGT.",
      blurb_en:"White-meat filefish, great HGT yield." }),
    P({ id:"tahali", cat:"pescado", es:"Tahalí (Pez Sable)", en:"Ribbonfish",
      sci:"Trichiurus lepturus", fao:"FAO 31 / 34", origin_es:"Atlántico", origin_en:"Atlantic",
      tags:["Bloque"], price:9.5, retail:true,
      pres_es:"Entero o HGT en IWP", pres_en:"Whole or HGT in IWP",
      pack_es:"A granel en cajas de 10 u 8 kg", pack_en:"Bulk in 10 or 8 kg boxes",
      blurb_es:"Pez cinta plateado, muy demandado en mercados asiáticos.",
      blurb_en:"Silver ribbonfish, in high demand across Asian markets." }),
    P({ id:"pargo", cat:"pescado", es:"Pargo Rojo del Caribe", en:"Caribbean Red Snapper",
      sci:"Lutjanus purpureus", fao:"FAO 31", origin_es:"Caribe", origin_en:"Caribbean",
      tags:["Bloque"], price:29.0, retail:true,
      sizes_es:"S 300–500 · M 500–700 · L 700 gr–1 kg a más", sizes_en:"S 300–500 · M 500–700 · L 700 gr–1 kg up",
      pres_es:"Entero WGGS en IWP", pres_en:"Whole WGGS in IWP",
      pack_es:"Entero en cajas de 10 o 20 lb", pack_en:"Whole in 10 or 20 lb boxes",
      blurb_es:"Pargo rojo de piel intensa, estrella de mesa premium.",
      blurb_en:"Deep-red snapper, a premium table star." }),
    P({ id:"pejerrey", cat:"pescado", es:"Pejerrey (Silverside)", en:"Silversmelt",
      sci:"Odontesthes regia", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF"], price:11.0, retail:true,
      sizes_es:"Entera 12 cm/pz a más", sizes_en:"Whole 12 cm/pc up",
      pres_es:"Entera con branquias · HG y HGT", pres_en:"Whole with gills · HG & HGT",
      pack_es:"IQF cajas de 20 lb: 20 bolsas de 1 lb", pack_en:"IQF 20 lb boxes: 20×1 lb bags",
      blurb_es:"Pejerrey IQF talla pareja, frito o a la plancha.",
      blurb_en:"Even-size IQF silverside, fried or grilled." }),
    P({ id:"corvina", cat:"pescado", es:"Corvina Amarilla", en:"Yellow Corvina",
      sci:"Cynoscion analis", fao:"FAO 31", origin_es:"Atlántico", origin_en:"Atlantic",
      tags:["IQF"], price:26.0, retail:true,
      sizes_es:"Filete 4–6 / 6–8 / 8–10 / 10–12 oz", sizes_en:"Fillet 4–6 / 6–8 / 8–10 / 10–12 oz",
      pres_es:"Entero o filete sin espinas", pres_en:"Whole or boneless fillets",
      pack_es:"IVP filetes en cajas de 10, 20 o 60 lb", pack_en:"IVP fillets in 10, 20 or 60 lb boxes",
      blurb_es:"Corvina de carne magra, filete IVP sin espinas.",
      blurb_en:"Lean corvina, boneless IVP fillet." }),
    P({ id:"pez-sierra", cat:"pescado", es:"Pez Sierra (Kingfish)", en:"Kingfish",
      sci:"Scomberomorus sierra", fao:"FAO 31", origin_es:"Pacífico", origin_en:"Pacific",
      tags:["IQF"], price:15.0, retail:true,
      sizes_es:"T1 3–5 · T2 5–10 · T3 10–15 lb a más", sizes_en:"T1 3–5 · T2 5–10 · T3 10–15 lb up",
      pres_es:"Entero o en ruedas", pres_en:"Whole or sliced",
      pack_es:"IWP en cajas de 60 lb", pack_en:"IWP in 60 lb boxes",
      blurb_es:"Sierra firme en ruedas, ideal para grill y ceviche.",
      blurb_en:"Firm kingfish steaks, ideal for grill and ceviche." }),

    // ----- MARISCOS / SHELLFISH -----
    P({ id:"concha", cat:"marisco", es:"Concha de Abanico", en:"Scallops",
      sci:"Argopecten purpuratus", fao:"FAO 87 · Acuicultura", origin_es:"Perú (Sechura)", origin_en:"Peru (Sechura)",
      tags:["IQF"], price:42.0, featured:true, retail:true,
      sizes_es:"Media concha 10–20 a 80–100 lb/pz", sizes_en:"Half shell 10–20 to 80–100 lb/pc",
      pres_es:"Tallo solo, tallo con coral o media concha", pres_en:"Roe off, roe on or half shell",
      pack_es:"Sin concha 20/30 lb (10×2 lb) · media concha caja máster 10 kg", pack_en:"No shell 20/30 lb (10×2 lb) · half shell 10 kg master box",
      blurb_es:"Concha de abanico de Sechura, dulce y carnosa. Acuicultura certificada.",
      blurb_en:"Sechura bay scallop, sweet and meaty. Certified aquaculture." }),
    P({ id:"langosta", cat:"marisco", es:"Langosta", en:"Lobster",
      sci:"Panulirus", fao:"FAO 31", origin_es:"Caribe", origin_en:"Caribbean",
      tags:["IQF"], price:95.0, featured:true, retail:true,
      sizes_es:"Entera T1 12–14 oz a T10 · cola T1 6 oz a más", sizes_en:"Whole T1 12–14 oz to T10 · tail T1 6 oz up",
      pres_es:"Entera cruda y cola cruda", pres_en:"Raw whole and raw tail",
      pack_es:"IWP en cajas", pack_en:"IWP in boxes",
      blurb_es:"Langosta cruda entera o cola, calibrada por tallas. Lujo de exportación.",
      blurb_en:"Raw whole lobster or tail, size-graded. Export luxury." }),
    P({ id:"pulpo", cat:"marisco", es:"Pulpo", en:"Octopus",
      sci:"Octopus mimus", fao:"FAO 34 / 31", origin_es:"Perú · África", origin_en:"Peru · Africa",
      tags:["IQF","Bloque"], price:33.0, featured:true, retail:true,
      sizes_es:"Entero T8 0,3 kg a T1 +4 kg · flor", sizes_en:"Whole T8 0.3 kg to T1 +4 kg · flower",
      pres_es:"Entero", pres_en:"Whole",
      pack_es:"Entero en sacos de 20 kg: 2 bloques de 10 kg", pack_en:"Whole in 20 kg bags: 2 blocks of 10 kg",
      blurb_es:"Pulpo entero por tallas, carne tierna. Corte flor a pedido.",
      blurb_en:"Whole octopus graded by size, tender meat. Flower cut on request." }),
    P({ id:"pulpo-bandeja", cat:"marisco", es:"Pulpo en Bandeja", en:"Octopus on Tray",
      sci:"Octopus mimus", fao:"FAO 34 / 31", origin_es:"Perú", origin_en:"Peru",
      tags:["IQF"], price:36.0, retail:true,
      sizes_es:"1–2 · 2–4 · 4–6 · 6–8 lb a más", sizes_en:"1–2 · 2–4 · 4–6 · 6–8 lb up",
      pres_es:"Entero en bandeja", pres_en:"Whole on tray",
      pack_es:"3 a 6 bandejas por caja según talla", pack_en:"3 to 6 trays per box by size",
      blurb_es:"Pulpo entero presentado en bandeja, retail premium.",
      blurb_en:"Whole octopus tray-packed, premium retail." }),
    P({ id:"pata-pulpo", cat:"marisco", es:"Pata de Pulpo Cocida", en:"Cooked Octopus Tentacle",
      sci:"Octopus vulgaris", fao:"FAO 34 / 31", origin_es:"España", origin_en:"Spain",
      tags:["IQF","Cocido"], price:58.0, retail:true,
      sizes_es:"T2 3–4 · T3 2–3 · T4 1,5–2 · T5 2 kg a más", sizes_en:"T2 3–4 · T3 2–3 · T4 1.5–2 · T5 2 kg up",
      pres_es:"Cocida", pres_en:"Cooked",
      pack_es:"Caja máster: 10 bolsas de 1 lb", pack_en:"Master box: 10×1 lb bags",
      blurb_es:"Pata de pulpo cocida estilo gallego, lista para emplatar.",
      blurb_en:"Galician-style cooked octopus leg, plate-ready." }),

    // ----- OVAS -----
    P({ id:"ovas", cat:"ovas", es:"Ovas de Pez Volador", en:"Flying Fish Roe",
      sci:"Cheilopogon", fao:"FAO 87", origin_es:"Perú", origin_en:"Peru",
      tags:["Bloque"], price:48.0, retail:true,
      pres_es:"Ovas individuales en bloque con 10% de sal, sin ovas negras", pres_en:"Individual roe in block, 10% salt, no black roe",
      pack_es:"Sacos de 20 kg: 2 bloques de 10 kg", pack_en:"20 kg bags: 2 blocks of 10 kg",
      blurb_es:"Tobiko natural en bloque, base para sushi y gourmet japonés.",
      blurb_en:"Natural tobiko in block, a base for sushi and Japanese gourmet." }),

    // ----- PREPARADOS -----
    P({ id:"romana", cat:"preparado", es:"Calamar a la Romana", en:"Battered Rings",
      sci:"Dosidicus gigas", fao:"FAO 87", origin_es:"España", origin_en:"Spain",
      tags:["IQF","Prefrito"], price:19.5, featured:true, retail:true,
      measure_es:"Diám. ext. 5–6 cm · int. 2,5–3 cm", measure_en:"Outer 5–6 cm · inner 2.5–3 cm",
      pres_es:"Prefritas y ultracongeladas", pres_en:"Pre-fried and deep-frozen",
      pack_es:"Bolsas de 0,5–1 kg o caja máster de 5 kg", pack_en:"0.5–1 kg bags or 5 kg master box",
      blurb_es:"Anilla rebozada lista para freír, valor agregado europeo.",
      blurb_en:"Battered ring ready to fry, European value-added." }),
    P({ id:"mix", cat:"preparado", es:"Preparado de Marisco", en:"Seafood Mix",
      sci:"Mix", fao:"FAO 87", origin_es:"España", origin_en:"Spain",
      tags:["IQF"], price:23.0, retail:true,
      pres_es:"Mejillón, dados mahi mahi, botones de pota, langostino, anilla y rodaja de pota", pres_en:"Mussel, mahi mahi cubes, squid buttons, prawn, squid rings & slices",
      pack_es:"Caja máster: 10 bolsas de 1 lb", pack_en:"Master box: 10×1 lb bags",
      blurb_es:"Mezcla de mariscos lista para paella, arroces y pastas.",
      blurb_en:"Ready seafood blend for paella, rice and pasta." }),
  ];

  // ---- Certificaciones & mercados ------------------------------------------
  const certs = ["HACCP", "SANIPES", "FDA", "BRCGS", "Unión Europea", "MSC Chain"];
  const markets = [
    { es:"Estados Unidos", en:"United States" },
    { es:"España", en:"Spain" },
    { es:"China", en:"China" },
    { es:"Japón", en:"Japan" },
    { es:"Italia", en:"Italy" },
    { es:"Corea del Sur", en:"South Korea" },
  ];

  // ---- i18n -----------------------------------------------------------------
  const i18n = {
    es: {
      nav_home:"Inicio", nav_catalog:"Catálogo", nav_about:"Nosotros", nav_export:"Exportación", nav_contact:"Contacto",
      search:"Buscar producto, especie o corte…",
      cta_catalog:"Ver catálogo", cta_quote:"Solicitar cotización",
      hero_eyebrow:"Exportador peruano de productos hidrobiológicos",
      hero_title:"Del mar del Perú al mundo, sin romper la cadena de frío.",
      hero_sub:"Pota, pescados, mariscos y preparados congelados con estándares HACCP y SANIPES. Compra directa para el mercado local y cotización para volumen de exportación.",
      stat_species:"Especies en línea", stat_markets:"Mercados de destino", stat_cold:"Cadena de frío", stat_years:"Trazabilidad total",
      cats_title:"Categorías destacadas", cats_sub:"Pota, pescados, mariscos, ovas y preparados — todo congelado bajo una misma cadena de frío.",
      cats_all:"Ver todo el catálogo",
      benefits_title:"Por qué Pycmar", benefits_sub:"Cuatro razones por las que clientes locales e internacionales confían en cada embarque.",
      ben1_t:"Calidad certificada", ben1_d:"Plantas con HACCP, SANIPES y habilitación FDA/UE. Control en cada lote.",
      ben2_t:"Cadena de frío", ben2_d:"Congelado IQF y en bloque a −18 °C, sin interrupción desde planta a contenedor.",
      ben3_t:"Capacidad exportadora", ben3_d:"Gestión operativa integral y tercerización para procesar a cualquier volumen.",
      ben4_t:"Trazabilidad", ben4_d:"Zona de captura FAO, talla y empaque documentados por producto.",
      featured_title:"Productos destacados", featured_sub:"Lo más solicitado por nuestros clientes.",
      trust_title:"Certificaciones y mercados", trust_sub:"Operamos bajo los estándares que exigen los mercados más estrictos.",
      cta_band_title:"¿Listo para tu próximo embarque?", cta_band_sub:"Cuéntanos qué necesitas y armamos tu cotización por contenedor o pedido local.",
      view_detail:"Ver detalle", add_quote:"Agregar a cotización", buy_now:"Comprar",
      filter_cat:"Categoría", filter_format:"Formato", filter_origin:"Origen", filter_clear:"Limpiar filtros",
      catalog_title:"Catálogo de productos", catalog_count:"productos",
      sort_label:"Ordenar", sort_featured:"Destacados", sort_az:"A — Z", sort_price_lo:"Precio: menor", sort_price_hi:"Precio: mayor",
      all:"Todos", per_kg:"x kg", from:"desde", quote_only:"Precio por cotización",
      spec_sci:"Nombre científico", spec_fao:"Zona de captura", spec_origin:"Origen", spec_format:"Formato",
      spec_pres:"Presentación", spec_measure:"Medidas", spec_sizes:"Tallas", spec_pack:"Empaquetado",
      qty:"Cantidad", related:"También te puede interesar", back_catalog:"Volver al catálogo",
      tab_buy:"Compra directa", tab_quote:"Cotización export",
      buy_note:"Precio local con IGV. Despacho refrigerado en Lima y provincias.",
      quote_note:"Para volumen y exportación: arma tu lista y solicita precio FOB/CFR.",
      cart_title:"Tu selección", cart_empty:"Aún no agregas productos.", cart_empty_cta:"Explorar catálogo",
      cart_buy:"Compra directa", cart_quote:"Cotización",
      subtotal:"Subtotal", checkout:"Ir a pagar", request_quote:"Enviar solicitud de cotización",
      remove:"Quitar", continue:"Seguir comprando",
      export_eyebrow:"Capacidades de exportación",
      export_title:"Una operación lista para el comercio internacional.",
      export_sub:"Gestionamos cada etapa de la cadena productiva con conocimiento técnico y logística de frío.",
      process_title:"Cómo trabajamos", logistics_title:"Logística y cobertura",
      contact_title:"Hablemos de tu pedido", contact_sub:"Respondemos cotizaciones en menos de 24 horas hábiles.",
      form_name:"Nombre y apellido", form_company:"Empresa", form_country:"País", form_email:"Correo",
      form_type:"Tipo de cliente", form_type_b2c:"Local / Minorista", form_type_b2b:"Exportación / Mayorista",
      form_volume:"Volumen estimado", form_message:"Mensaje", form_send:"Enviar solicitud", form_whatsapp:"Escríbenos por WhatsApp",
      checkout_title:"Pago seguro", pay_card:"Tarjeta", pay_wallet:"Yape / PLIN", pay_intl:"PayPal / Internacional",
      pay_pay:"Pagar", order_ok:"¡Pedido recibido!", order_ok_sub:"Te enviamos la confirmación a tu correo.",
      quote_ok:"¡Solicitud enviada!", quote_ok_sub:"Nuestro equipo comercial te contactará en menos de 24 h.",
      added:"Agregado", lang:"ES", footer_rights:"Todos los derechos reservados.",
      footer_explore:"Explora", footer_company:"Empresa", footer_contact:"Contacto",
      footer_about:"Nosotros", footer_certs:"Certificaciones", footer_quality:"Calidad",
    },
    en: {
      nav_home:"Home", nav_catalog:"Catalog", nav_about:"About", nav_export:"Export", nav_contact:"Contact",
      search:"Search product, species or cut…",
      cta_catalog:"View catalog", cta_quote:"Request a quote",
      hero_eyebrow:"Peruvian exporter of hydrobiological products",
      hero_title:"From Peru's sea to the world, without breaking the cold chain.",
      hero_sub:"Squid, fish, shellfish and value-added frozen seafood under HACCP and SANIPES standards. Direct purchase for the local market and quotes for export volume.",
      stat_species:"Species in line", stat_markets:"Destination markets", stat_cold:"Cold chain", stat_years:"Full traceability",
      cats_title:"Featured categories", cats_sub:"Squid, fish, shellfish, roe and value-added — all frozen under a single cold chain.",
      cats_all:"View full catalog",
      benefits_title:"Why Pycmar", benefits_sub:"Four reasons local and international clients trust every single shipment.",
      ben1_t:"Certified quality", ben1_d:"HACCP & SANIPES plants with FDA/EU approval. Control in every batch.",
      ben2_t:"Cold chain", ben2_d:"IQF and block freezing at −18 °C, unbroken from plant to container.",
      ben3_t:"Export capacity", ben3_d:"Full operational management and outsourcing to process at any volume.",
      ben4_t:"Traceability", ben4_d:"FAO capture zone, size and packaging documented per product.",
      featured_title:"Featured products", featured_sub:"The most requested by our clients.",
      trust_title:"Certifications & markets", trust_sub:"We operate under the standards the strictest markets demand.",
      cta_band_title:"Ready for your next shipment?", cta_band_sub:"Tell us what you need and we'll build your quote by container or local order.",
      view_detail:"View detail", add_quote:"Add to quote", buy_now:"Buy now",
      filter_cat:"Category", filter_format:"Format", filter_origin:"Origin", filter_clear:"Clear filters",
      catalog_title:"Product catalog", catalog_count:"products",
      sort_label:"Sort", sort_featured:"Featured", sort_az:"A — Z", sort_price_lo:"Price: low", sort_price_hi:"Price: high",
      all:"All", per_kg:"per kg", from:"from", quote_only:"Price on request",
      spec_sci:"Scientific name", spec_fao:"Capture zone", spec_origin:"Origin", spec_format:"Format",
      spec_pres:"Presentation", spec_measure:"Measurements", spec_sizes:"Sizes", spec_pack:"Packaging",
      qty:"Quantity", related:"You may also like", back_catalog:"Back to catalog",
      tab_buy:"Direct purchase", tab_quote:"Export quote",
      buy_note:"Local price incl. tax. Refrigerated delivery in Lima and provinces.",
      quote_note:"For volume & export: build your list and request FOB/CFR pricing.",
      cart_title:"Your selection", cart_empty:"You haven't added products yet.", cart_empty_cta:"Explore catalog",
      cart_buy:"Direct purchase", cart_quote:"Quote",
      subtotal:"Subtotal", checkout:"Checkout", request_quote:"Send quote request",
      remove:"Remove", continue:"Continue shopping",
      export_eyebrow:"Export capabilities",
      export_title:"An operation ready for international trade.",
      export_sub:"We manage every stage of the production chain with technical know-how and cold logistics.",
      process_title:"How we work", logistics_title:"Logistics & coverage",
      contact_title:"Let's talk about your order", contact_sub:"We answer quotes in under 24 business hours.",
      form_name:"Full name", form_company:"Company", form_country:"Country", form_email:"Email",
      form_type:"Client type", form_type_b2c:"Local / Retail", form_type_b2b:"Export / Wholesale",
      form_volume:"Estimated volume", form_message:"Message", form_send:"Send request", form_whatsapp:"Message us on WhatsApp",
      checkout_title:"Secure payment", pay_card:"Card", pay_wallet:"Yape / PLIN", pay_intl:"PayPal / International",
      pay_pay:"Pay", order_ok:"Order received!", order_ok_sub:"We've sent the confirmation to your email.",
      quote_ok:"Request sent!", quote_ok_sub:"Our sales team will contact you within 24 h.",
      added:"Added", lang:"EN", footer_rights:"All rights reserved.",
      footer_explore:"Explore", footer_company:"Company", footer_contact:"Contact",
      footer_about:"About us", footer_certs:"Certifications", footer_quality:"Quality",
    },
  };

  window.PY = { company, categories, products, certs, markets, i18n };
})();
